services:

  database:
    container_name: laravel-docker-database
    image: mariadb:lts
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
    volumes:
      - ./devops/mariadb/custom.cnf:/etc/mysql/custom.cnf
      - db-data:/var/lib/mysql/
    ports:
      - "${DOCKER_DATABASE_PORT:-3310}:3306"
    networks:
      - laravel-docker-network
    tty: "true"
    restart: unless-stopped

  dbadmin:
    container_name: laravel-docker-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - "${DOCKER_DBADMIN_PORT:-8888}:80"
    environment:
      PMA_HOST: database
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel-docker-network
    tty: true
    restart: unless-stopped

  redis:
    container_name: laravel-docker-redis
    image: redis:7-alpine
    ports:
      - "${DOCKER_REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - laravel-docker-network
    tty: "true"
    restart: unless-stopped

  webserver:
    container_name: laravel-docker-nginx
    image: nginx:stable-alpine
    ports:
      - "${DOCKER_APPSERVER_PORT:-80}:80"
    volumes:
      - ./:/var/www/html
      - ./devops/nginx/conf.d/:/etc/nginx/conf.d/
      - ./devops/logs/nginx:/var/log/nginx
    networks:
      - laravel-docker-network
    tty: "true"
    restart: unless-stopped

  app:
    container_name: laravel-docker-app
    image: laravel-docker/app:${DOCKER_APP_VERSION:-1.0.0}
    build:
      args:
        PHP_VERSION: ${DOCKER_PHP_VERSION:-8.2}
        user: laravel
        uid: 1000
      context: .
      dockerfile: ./devops/php/Dockerfile
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: local
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./devops/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      # - ./devops/php/conf.d/disable-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    depends_on:
      - database
      - webserver
    networks:
      - laravel-docker-network
    tty: "true"
    restart: unless-stopped

  supervisor:
    container_name: laravel-docker-supervisor
    image: laravel-docker/supervisord:${DOCKER_APP_VERSION:-1.0.0}
    build:
      args:
        PHP_VERSION: ${DOCKER_PHP_VERSION:-8.2}
      context: .
      dockerfile: ./devops/supervisord/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./devops/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./devops/logs/supervisord/:/etc/supervisor/logs/
    depends_on:
      - app
    networks:
      - laravel-docker-network
    # network_mode: host
    tty: "true"
    restart: unless-stopped

networks:

  laravel-docker-network:
    driver: bridge

volumes:

  db-data:
    driver: local

  redis-data:
    driver: local
